### ISSUE TITLE
Crash with Battletowers (1.16)

### ISSUE THREAD

**Issue by MrKashew** [emilyploszaj/step-height-entity-attribute#1]
[Crashlog](https://gist.github.com/MrKashew/ceb42f1ff1d77cfd46580cf4d1f040a2)

I was suggested that the issue is with [this code](https://github.com/emilyploszaj/step-height-entity-attribute/blob/4e9753a3ac6aa0e8a3f918000eee596f05fbc9da/src/main/java/dev/emi/stepheightentityattribute/mixin/LivingEntityMixin.java#L24) assuming  every `LivingEntity` calls `createLivingAttributes` -  can be fixed by adding a check to make sure the attribute is available before accessing it perhaps.

I love your trinkets mods and battletowers likewise I hope this compatibility can be fixed!

**Comment by emilyploszaj** [comment]
This seems to have been fixed by Draylar https://github.com/Draylar/battle-towers/commit/8a1c6b66001d60f344f6a9478b4843351c30bc55
