### ISSUE TITLE
Incompatibility with Earthbounds

### ISSUE THREAD

**Issue by Klyser8** [emilyploszaj/step-height-entity-attribute#4]
Hey,

I am creating an issue as I have been reported some conflict that happens when both this mod and my mod are present.

You can read about it here https://github.com/Klyser8/Earthbounds/issues/1

**Comment by TheButterbrotMan** [comment]
https://bytebin.lucko.me/IZbIygbeb8

**Comment by emilyploszaj** [comment]
finally figured this out, you're not creating mob attributes despite creating living entities, I guess I need to do a null chuck because not all modders will play safe

**Comment by Klyser8** [comment]
Yup, I gotta create the mob attributes separately since different variants have different attributes. Good catch though!
